language: node_js
node_js:
  - "11"

before_deploy:
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  name: Auto Deploy through Travis
  target-branch: gh-pages
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

env:
- KATAS_SERVICE_URL=https://yunqiangwu.github.io/katas
